<?php
require_once __DIR__ . '/../../middleware/auth.php'; require_once __DIR__ . '/../../database/Database.php'; require_once __DIR__ . '/../../layouts/role_dashboard.php'; require_auth(['teacher']);
$user=auth_user(); $teacherId=(int)($user['id']??0); $csrf=csrf_token(); $db=Database::connection();
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verify_csrf($_POST['_csrf'] ?? '')){flash_set('error','Xavfsizlik xato'); redirect('/test/teacher/tests.php');}
 $id=(int)($_POST['id']??0); $testId=(int)($_POST['test_id']??0); $q=trim((string)($_POST['question_text']??'')); $a=trim((string)($_POST['option_a']??''));$b=trim((string)($_POST['option_b']??''));$c=trim((string)($_POST['option_c']??''));$d=trim((string)($_POST['option_d']??''));$co=trim((string)($_POST['correct_option']??'')); if(!in_array($co,['A','B','C','D'],true))$co=null;
 $st=$db->prepare('UPDATE test_questions SET question_text=?,option_a=?,option_b=?,option_c=?,option_d=?,correct_option=?,updated_at=NOW() WHERE id=? AND teacher_id=? LIMIT 1'); $st->bind_param('ssssssii',$q,$a,$b,$c,$d,$co,$id,$teacherId); $st->execute(); $st->close(); flash_set('success','Savol yangilandi.'); redirect('/test/teacher/test-questions.php?test_id='.$testId);
}
$id=(int)($_GET['id']??0); $testId=(int)($_GET['test_id']??0); $st=$db->prepare('SELECT * FROM test_questions WHERE id=? AND teacher_id=? LIMIT 1'); $st->bind_param('ii',$id,$teacherId); $st->execute(); $q=$st->get_result()->fetch_assoc(); $st->close();
ob_start(); ?>
<section class="rounded-2xl border bg-white p-5"><a href="/test/teacher/test-questions.php?test_id=<?= (int)$testId ?>" class="rounded-xl border px-3 py-2 text-sm">Orqaga</a><form class="mt-4 space-y-2" method="POST"><input type="hidden" name="_csrf" value="<?= h($csrf) ?>"><input type="hidden" name="id" value="<?= (int)$id ?>"><input type="hidden" name="test_id" value="<?= (int)$testId ?>"><textarea name="question_text" class="w-full rounded-xl border px-3 py-2" required><?= h($q['question_text']??'') ?></textarea><input name="option_a" class="w-full rounded-xl border px-3 py-2" value="<?= h($q['option_a']??'') ?>"><input name="option_b" class="w-full rounded-xl border px-3 py-2" value="<?= h($q['option_b']??'') ?>"><input name="option_c" class="w-full rounded-xl border px-3 py-2" value="<?= h($q['option_c']??'') ?>"><input name="option_d" class="w-full rounded-xl border px-3 py-2" value="<?= h($q['option_d']??'') ?>"><select name="correct_option" class="w-full rounded-xl border px-3 py-2"><option value="">Tanlang</option><?php foreach(['A','B','C','D'] as $x): ?><option value="<?= $x ?>" <?= (($q['correct_option']??'')===$x)?'selected':'' ?>><?= $x ?></option><?php endforeach; ?></select><button class="rounded-xl bg-green-700 px-4 py-2 text-white">Saqlash</button></form></section>
<?php $content=ob_get_clean(); render_dashboard_layout(['title'=>'Savol edit','page_title'=>'Savol tahrirlash','subtitle'=>'','role_name'=>'Teacher','menu'=>[['key'=>'tests','label'=>'Testlar','icon'=>'tests','href'=>'/test/teacher/tests.php']],'active'=>'tests','user'=>$user,'content'=>$content]);
